joint_state_controller:
  type: "joint_state_controller/JointStateController"
  publish_rate: 5

drive_controller:
  type: "diff_drive_controller/DiffDriveController"
  left_wheel: ['front_left_wheel_joint', 'rear_left_wheel_joint']
  right_wheel: ['front_right_wheel_joint', 'rear_right_wheel_joint']
  publish_rate: 5
  pose_covariance_diagonal: [0.001, 0.001, 1000000.0, 1000000.0, 1000000.0, 0.03]
  twist_covariance_diagonal: [0.001, 0.001, 0.001, 1000000.0, 1000000.0, 0.03]
  cmd_vel_timeout: 0.25
  velocity_rolling_window_size: 10
  publish_cmd: true
  enable_odom_tf: false
  base_frame_id: base_link
  odom_frame_id: odom

  # Odometry fused with IMU is published by robot_localization, so
  # no need to publish a TF based on encoders alone.

  # Wheel separation and radius multipliers
  # Auto read will fail due to suspension link and using diagonal since the platform is skid-steer
  wheel_separation: 0.28
  wheel_radius: 0.40
  wheel_separation_multiplier: 1.0 # default: 1.0
  wheel_radius_multiplier    : 1.0 # default: 1.0



  # Velocity and acceleration limits
  # Whenever a min_* is unspecified, default to -max_*
  linear:
    x:
      has_velocity_limits    : false
      max_velocity           : 5.0   # m/s
      has_acceleration_limits: false
      max_acceleration       : 50.0   # m/s^2
  angular:
    z:
      has_velocity_limits    : false
      max_velocity           : 4.0   # rad/s
      has_acceleration_limits: false
      max_acceleration       : 40.0   # rad/s^2

ekf_localization:
  frequency: 50
  two_d_mode: true
  odom0: /odom
  odom0_config: [false, false, false,
                false, false, false,
                true, true, true,
                false, false, true,
                false, false, false]
  odom0_differential: false
  odom0_queue_size: 10

  imu0: imu/data
  imu0_config: [false, false, false,
                true, true, true,
                false, false, false,
                true, true, true,
                false, false, false]
  imu0_differential: true
  imu0_queue_size: 10
  imu0_remove_gravitational_acceleration: true
  odom_frame: map
  base_link_frame: base_link
  publish_tf: true
  two_d_mode: true