// Generated by gencpp from file patrolling_sim/GoToStartPosSrvResponse.msg
// DO NOT EDIT!


#ifndef PATROLLING_SIM_MESSAGE_GOTOSTARTPOSSRVRESPONSE_H
#define PATROLLING_SIM_MESSAGE_GOTOSTARTPOSSRVRESPONSE_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace patrolling_sim
{
template <class ContainerAllocator>
struct GoToStartPosSrvResponse_
{
  typedef GoToStartPosSrvResponse_<ContainerAllocator> Type;

  GoToStartPosSrvResponse_()
    {
    }
  GoToStartPosSrvResponse_(const ContainerAllocator& _alloc)
    {
  (void)_alloc;
    }







  typedef boost::shared_ptr< ::patrolling_sim::GoToStartPosSrvResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::patrolling_sim::GoToStartPosSrvResponse_<ContainerAllocator> const> ConstPtr;

}; // struct GoToStartPosSrvResponse_

typedef ::patrolling_sim::GoToStartPosSrvResponse_<std::allocator<void> > GoToStartPosSrvResponse;

typedef boost::shared_ptr< ::patrolling_sim::GoToStartPosSrvResponse > GoToStartPosSrvResponsePtr;
typedef boost::shared_ptr< ::patrolling_sim::GoToStartPosSrvResponse const> GoToStartPosSrvResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::patrolling_sim::GoToStartPosSrvResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::patrolling_sim::GoToStartPosSrvResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}


} // namespace patrolling_sim

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::patrolling_sim::GoToStartPosSrvResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::patrolling_sim::GoToStartPosSrvResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::patrolling_sim::GoToStartPosSrvResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::patrolling_sim::GoToStartPosSrvResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::patrolling_sim::GoToStartPosSrvResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::patrolling_sim::GoToStartPosSrvResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::patrolling_sim::GoToStartPosSrvResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "d41d8cd98f00b204e9800998ecf8427e";
  }

  static const char* value(const ::patrolling_sim::GoToStartPosSrvResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xd41d8cd98f00b204ULL;
  static const uint64_t static_value2 = 0xe9800998ecf8427eULL;
};

template<class ContainerAllocator>
struct DataType< ::patrolling_sim::GoToStartPosSrvResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "patrolling_sim/GoToStartPosSrvResponse";
  }

  static const char* value(const ::patrolling_sim::GoToStartPosSrvResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::patrolling_sim::GoToStartPosSrvResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "\n"
;
  }

  static const char* value(const ::patrolling_sim::GoToStartPosSrvResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::patrolling_sim::GoToStartPosSrvResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream&, T)
    {}

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct GoToStartPosSrvResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::patrolling_sim::GoToStartPosSrvResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream&, const std::string&, const ::patrolling_sim::GoToStartPosSrvResponse_<ContainerAllocator>&)
  {}
};

} // namespace message_operations
} // namespace ros

#endif // PATROLLING_SIM_MESSAGE_GOTOSTARTPOSSRVRESPONSE_H
