// Generated by gencpp from file agrosim/centralised.msg
// DO NOT EDIT!


#ifndef AGROSIM_MESSAGE_CENTRALISED_H
#define AGROSIM_MESSAGE_CENTRALISED_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace agrosim
{
template <class ContainerAllocator>
struct centralised_
{
  typedef centralised_<ContainerAllocator> Type;

  centralised_()
    : Id(0)
    , pos_x(0.0)
    , pos_y(0.0)  {
    }
  centralised_(const ContainerAllocator& _alloc)
    : Id(0)
    , pos_x(0.0)
    , pos_y(0.0)  {
  (void)_alloc;
    }



   typedef int32_t _Id_type;
  _Id_type Id;

   typedef double _pos_x_type;
  _pos_x_type pos_x;

   typedef double _pos_y_type;
  _pos_y_type pos_y;





  typedef boost::shared_ptr< ::agrosim::centralised_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::agrosim::centralised_<ContainerAllocator> const> ConstPtr;

}; // struct centralised_

typedef ::agrosim::centralised_<std::allocator<void> > centralised;

typedef boost::shared_ptr< ::agrosim::centralised > centralisedPtr;
typedef boost::shared_ptr< ::agrosim::centralised const> centralisedConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::agrosim::centralised_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::agrosim::centralised_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::agrosim::centralised_<ContainerAllocator1> & lhs, const ::agrosim::centralised_<ContainerAllocator2> & rhs)
{
  return lhs.Id == rhs.Id &&
    lhs.pos_x == rhs.pos_x &&
    lhs.pos_y == rhs.pos_y;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::agrosim::centralised_<ContainerAllocator1> & lhs, const ::agrosim::centralised_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace agrosim

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::agrosim::centralised_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::agrosim::centralised_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::agrosim::centralised_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::agrosim::centralised_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::agrosim::centralised_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::agrosim::centralised_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::agrosim::centralised_<ContainerAllocator> >
{
  static const char* value()
  {
    return "75665f1d63018aac0cb32965c9ec19d2";
  }

  static const char* value(const ::agrosim::centralised_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x75665f1d63018aacULL;
  static const uint64_t static_value2 = 0x0cb32965c9ec19d2ULL;
};

template<class ContainerAllocator>
struct DataType< ::agrosim::centralised_<ContainerAllocator> >
{
  static const char* value()
  {
    return "agrosim/centralised";
  }

  static const char* value(const ::agrosim::centralised_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::agrosim::centralised_<ContainerAllocator> >
{
  static const char* value()
  {
    return "int32 Id\n"
"float64 pos_x\n"
"float64 pos_y\n"
;
  }

  static const char* value(const ::agrosim::centralised_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::agrosim::centralised_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.Id);
      stream.next(m.pos_x);
      stream.next(m.pos_y);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct centralised_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::agrosim::centralised_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::agrosim::centralised_<ContainerAllocator>& v)
  {
    s << indent << "Id: ";
    Printer<int32_t>::stream(s, indent + "  ", v.Id);
    s << indent << "pos_x: ";
    Printer<double>::stream(s, indent + "  ", v.pos_x);
    s << indent << "pos_y: ";
    Printer<double>::stream(s, indent + "  ", v.pos_y);
  }
};

} // namespace message_operations
} // namespace ros

#endif // AGROSIM_MESSAGE_CENTRALISED_H
