// Generated by gencpp from file agrosim/Cost.msg
// DO NOT EDIT!


#ifndef AGROSIM_MESSAGE_COST_H
#define AGROSIM_MESSAGE_COST_H

#include <ros/service_traits.h>


#include <agrosim/CostRequest.h>
#include <agrosim/CostResponse.h>


namespace agrosim
{

struct Cost
{

typedef CostRequest Request;
typedef CostResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct Cost
} // namespace agrosim


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::agrosim::Cost > {
  static const char* value()
  {
    return "c231a7c7ef297dd0990c7c10eb4d3e0e";
  }

  static const char* value(const ::agrosim::Cost&) { return value(); }
};

template<>
struct DataType< ::agrosim::Cost > {
  static const char* value()
  {
    return "agrosim/Cost";
  }

  static const char* value(const ::agrosim::Cost&) { return value(); }
};


// service_traits::MD5Sum< ::agrosim::CostRequest> should match
// service_traits::MD5Sum< ::agrosim::Cost >
template<>
struct MD5Sum< ::agrosim::CostRequest>
{
  static const char* value()
  {
    return MD5Sum< ::agrosim::Cost >::value();
  }
  static const char* value(const ::agrosim::CostRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::agrosim::CostRequest> should match
// service_traits::DataType< ::agrosim::Cost >
template<>
struct DataType< ::agrosim::CostRequest>
{
  static const char* value()
  {
    return DataType< ::agrosim::Cost >::value();
  }
  static const char* value(const ::agrosim::CostRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::agrosim::CostResponse> should match
// service_traits::MD5Sum< ::agrosim::Cost >
template<>
struct MD5Sum< ::agrosim::CostResponse>
{
  static const char* value()
  {
    return MD5Sum< ::agrosim::Cost >::value();
  }
  static const char* value(const ::agrosim::CostResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::agrosim::CostResponse> should match
// service_traits::DataType< ::agrosim::Cost >
template<>
struct DataType< ::agrosim::CostResponse>
{
  static const char* value()
  {
    return DataType< ::agrosim::Cost >::value();
  }
  static const char* value(const ::agrosim::CostResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // AGROSIM_MESSAGE_COST_H
