// Generated by gencpp from file agrosim/DecisionResponse.msg
// DO NOT EDIT!


#ifndef AGROSIM_MESSAGE_DECISIONRESPONSE_H
#define AGROSIM_MESSAGE_DECISIONRESPONSE_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace agrosim
{
template <class ContainerAllocator>
struct DecisionResponse_
{
  typedef DecisionResponse_<ContainerAllocator> Type;

  DecisionResponse_()
    : Verification(false)  {
    }
  DecisionResponse_(const ContainerAllocator& _alloc)
    : Verification(false)  {
  (void)_alloc;
    }



   typedef uint8_t _Verification_type;
  _Verification_type Verification;





  typedef boost::shared_ptr< ::agrosim::DecisionResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::agrosim::DecisionResponse_<ContainerAllocator> const> ConstPtr;

}; // struct DecisionResponse_

typedef ::agrosim::DecisionResponse_<std::allocator<void> > DecisionResponse;

typedef boost::shared_ptr< ::agrosim::DecisionResponse > DecisionResponsePtr;
typedef boost::shared_ptr< ::agrosim::DecisionResponse const> DecisionResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::agrosim::DecisionResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::agrosim::DecisionResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::agrosim::DecisionResponse_<ContainerAllocator1> & lhs, const ::agrosim::DecisionResponse_<ContainerAllocator2> & rhs)
{
  return lhs.Verification == rhs.Verification;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::agrosim::DecisionResponse_<ContainerAllocator1> & lhs, const ::agrosim::DecisionResponse_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace agrosim

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::agrosim::DecisionResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::agrosim::DecisionResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::agrosim::DecisionResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::agrosim::DecisionResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::agrosim::DecisionResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::agrosim::DecisionResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::agrosim::DecisionResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "baaf30877b8ac9ad6ddd9e2b335d0855";
  }

  static const char* value(const ::agrosim::DecisionResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xbaaf30877b8ac9adULL;
  static const uint64_t static_value2 = 0x6ddd9e2b335d0855ULL;
};

template<class ContainerAllocator>
struct DataType< ::agrosim::DecisionResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "agrosim/DecisionResponse";
  }

  static const char* value(const ::agrosim::DecisionResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::agrosim::DecisionResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "bool Verification\n"
"\n"
;
  }

  static const char* value(const ::agrosim::DecisionResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::agrosim::DecisionResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.Verification);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct DecisionResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::agrosim::DecisionResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::agrosim::DecisionResponse_<ContainerAllocator>& v)
  {
    s << indent << "Verification: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.Verification);
  }
};

} // namespace message_operations
} // namespace ros

#endif // AGROSIM_MESSAGE_DECISIONRESPONSE_H
