// Generated by gencpp from file agrosim/Decision.msg
// DO NOT EDIT!


#ifndef AGROSIM_MESSAGE_DECISION_H
#define AGROSIM_MESSAGE_DECISION_H

#include <ros/service_traits.h>


#include <agrosim/DecisionRequest.h>
#include <agrosim/DecisionResponse.h>


namespace agrosim
{

struct Decision
{

typedef DecisionRequest Request;
typedef DecisionResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct Decision
} // namespace agrosim


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::agrosim::Decision > {
  static const char* value()
  {
    return "654ef0f93a4707fa911e286e21ab84e9";
  }

  static const char* value(const ::agrosim::Decision&) { return value(); }
};

template<>
struct DataType< ::agrosim::Decision > {
  static const char* value()
  {
    return "agrosim/Decision";
  }

  static const char* value(const ::agrosim::Decision&) { return value(); }
};


// service_traits::MD5Sum< ::agrosim::DecisionRequest> should match
// service_traits::MD5Sum< ::agrosim::Decision >
template<>
struct MD5Sum< ::agrosim::DecisionRequest>
{
  static const char* value()
  {
    return MD5Sum< ::agrosim::Decision >::value();
  }
  static const char* value(const ::agrosim::DecisionRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::agrosim::DecisionRequest> should match
// service_traits::DataType< ::agrosim::Decision >
template<>
struct DataType< ::agrosim::DecisionRequest>
{
  static const char* value()
  {
    return DataType< ::agrosim::Decision >::value();
  }
  static const char* value(const ::agrosim::DecisionRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::agrosim::DecisionResponse> should match
// service_traits::MD5Sum< ::agrosim::Decision >
template<>
struct MD5Sum< ::agrosim::DecisionResponse>
{
  static const char* value()
  {
    return MD5Sum< ::agrosim::Decision >::value();
  }
  static const char* value(const ::agrosim::DecisionResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::agrosim::DecisionResponse> should match
// service_traits::DataType< ::agrosim::Decision >
template<>
struct DataType< ::agrosim::DecisionResponse>
{
  static const char* value()
  {
    return DataType< ::agrosim::Decision >::value();
  }
  static const char* value(const ::agrosim::DecisionResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // AGROSIM_MESSAGE_DECISION_H
