// Generated by gencpp from file agrosim/descentralised.msg
// DO NOT EDIT!


#ifndef AGROSIM_MESSAGE_DESCENTRALISED_H
#define AGROSIM_MESSAGE_DESCENTRALISED_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <agrosim/neighbour.h>

namespace agrosim
{
template <class ContainerAllocator>
struct descentralised_
{
  typedef descentralised_<ContainerAllocator> Type;

  descentralised_()
    : Id(0)
    , pos_x(0.0)
    , pos_y(0.0)
    , task(0)
    , cost(0.0)
    , taskdone()
    , others()  {
    }
  descentralised_(const ContainerAllocator& _alloc)
    : Id(0)
    , pos_x(0.0)
    , pos_y(0.0)
    , task(0)
    , cost(0.0)
    , taskdone(_alloc)
    , others(_alloc)  {
  (void)_alloc;
    }



   typedef int32_t _Id_type;
  _Id_type Id;

   typedef double _pos_x_type;
  _pos_x_type pos_x;

   typedef double _pos_y_type;
  _pos_y_type pos_y;

   typedef int32_t _task_type;
  _task_type task;

   typedef double _cost_type;
  _cost_type cost;

   typedef std::vector<int32_t, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<int32_t>> _taskdone_type;
  _taskdone_type taskdone;

   typedef  ::agrosim::neighbour_<ContainerAllocator>  _others_type;
  _others_type others;





  typedef boost::shared_ptr< ::agrosim::descentralised_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::agrosim::descentralised_<ContainerAllocator> const> ConstPtr;

}; // struct descentralised_

typedef ::agrosim::descentralised_<std::allocator<void> > descentralised;

typedef boost::shared_ptr< ::agrosim::descentralised > descentralisedPtr;
typedef boost::shared_ptr< ::agrosim::descentralised const> descentralisedConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::agrosim::descentralised_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::agrosim::descentralised_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::agrosim::descentralised_<ContainerAllocator1> & lhs, const ::agrosim::descentralised_<ContainerAllocator2> & rhs)
{
  return lhs.Id == rhs.Id &&
    lhs.pos_x == rhs.pos_x &&
    lhs.pos_y == rhs.pos_y &&
    lhs.task == rhs.task &&
    lhs.cost == rhs.cost &&
    lhs.taskdone == rhs.taskdone &&
    lhs.others == rhs.others;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::agrosim::descentralised_<ContainerAllocator1> & lhs, const ::agrosim::descentralised_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace agrosim

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::agrosim::descentralised_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::agrosim::descentralised_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::agrosim::descentralised_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::agrosim::descentralised_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::agrosim::descentralised_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::agrosim::descentralised_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::agrosim::descentralised_<ContainerAllocator> >
{
  static const char* value()
  {
    return "26872adb2b4262c73d17f57e4c48e1dc";
  }

  static const char* value(const ::agrosim::descentralised_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x26872adb2b4262c7ULL;
  static const uint64_t static_value2 = 0x3d17f57e4c48e1dcULL;
};

template<class ContainerAllocator>
struct DataType< ::agrosim::descentralised_<ContainerAllocator> >
{
  static const char* value()
  {
    return "agrosim/descentralised";
  }

  static const char* value(const ::agrosim::descentralised_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::agrosim::descentralised_<ContainerAllocator> >
{
  static const char* value()
  {
    return "int32 Id\n"
"float64 pos_x\n"
"float64 pos_y\n"
"int32 task\n"
"float64 cost\n"
"int32[] taskdone\n"
"agrosim/neighbour others\n"
"\n"
"\n"
"================================================================================\n"
"MSG: agrosim/neighbour\n"
"int32[] Id\n"
"int32[] Task\n"
"int32 row\n"
"int32 column\n"
"float64[]  costs\n"
;
  }

  static const char* value(const ::agrosim::descentralised_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::agrosim::descentralised_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.Id);
      stream.next(m.pos_x);
      stream.next(m.pos_y);
      stream.next(m.task);
      stream.next(m.cost);
      stream.next(m.taskdone);
      stream.next(m.others);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct descentralised_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::agrosim::descentralised_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::agrosim::descentralised_<ContainerAllocator>& v)
  {
    s << indent << "Id: ";
    Printer<int32_t>::stream(s, indent + "  ", v.Id);
    s << indent << "pos_x: ";
    Printer<double>::stream(s, indent + "  ", v.pos_x);
    s << indent << "pos_y: ";
    Printer<double>::stream(s, indent + "  ", v.pos_y);
    s << indent << "task: ";
    Printer<int32_t>::stream(s, indent + "  ", v.task);
    s << indent << "cost: ";
    Printer<double>::stream(s, indent + "  ", v.cost);
    s << indent << "taskdone[]" << std::endl;
    for (size_t i = 0; i < v.taskdone.size(); ++i)
    {
      s << indent << "  taskdone[" << i << "]: ";
      Printer<int32_t>::stream(s, indent + "  ", v.taskdone[i]);
    }
    s << indent << "others: ";
    s << std::endl;
    Printer< ::agrosim::neighbour_<ContainerAllocator> >::stream(s, indent + "  ", v.others);
  }
};

} // namespace message_operations
} // namespace ros

#endif // AGROSIM_MESSAGE_DESCENTRALISED_H
