// Generated by gencpp from file agrosim/distributed.msg
// DO NOT EDIT!


#ifndef AGROSIM_MESSAGE_DISTRIBUTED_H
#define AGROSIM_MESSAGE_DISTRIBUTED_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace agrosim
{
template <class ContainerAllocator>
struct distributed_
{
  typedef distributed_<ContainerAllocator> Type;

  distributed_()
    : Id(0)
    , pos_x(0.0)
    , pos_y(0.0)
    , Costs()
    , taskdone()  {
    }
  distributed_(const ContainerAllocator& _alloc)
    : Id(0)
    , pos_x(0.0)
    , pos_y(0.0)
    , Costs(_alloc)
    , taskdone(_alloc)  {
  (void)_alloc;
    }



   typedef int32_t _Id_type;
  _Id_type Id;

   typedef double _pos_x_type;
  _pos_x_type pos_x;

   typedef double _pos_y_type;
  _pos_y_type pos_y;

   typedef std::vector<double, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<double>> _Costs_type;
  _Costs_type Costs;

   typedef std::vector<int32_t, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<int32_t>> _taskdone_type;
  _taskdone_type taskdone;





  typedef boost::shared_ptr< ::agrosim::distributed_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::agrosim::distributed_<ContainerAllocator> const> ConstPtr;

}; // struct distributed_

typedef ::agrosim::distributed_<std::allocator<void> > distributed;

typedef boost::shared_ptr< ::agrosim::distributed > distributedPtr;
typedef boost::shared_ptr< ::agrosim::distributed const> distributedConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::agrosim::distributed_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::agrosim::distributed_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::agrosim::distributed_<ContainerAllocator1> & lhs, const ::agrosim::distributed_<ContainerAllocator2> & rhs)
{
  return lhs.Id == rhs.Id &&
    lhs.pos_x == rhs.pos_x &&
    lhs.pos_y == rhs.pos_y &&
    lhs.Costs == rhs.Costs &&
    lhs.taskdone == rhs.taskdone;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::agrosim::distributed_<ContainerAllocator1> & lhs, const ::agrosim::distributed_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace agrosim

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::agrosim::distributed_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::agrosim::distributed_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::agrosim::distributed_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::agrosim::distributed_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::agrosim::distributed_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::agrosim::distributed_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::agrosim::distributed_<ContainerAllocator> >
{
  static const char* value()
  {
    return "c9bb0f30a8a9f957e8ed5112fb6abd78";
  }

  static const char* value(const ::agrosim::distributed_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xc9bb0f30a8a9f957ULL;
  static const uint64_t static_value2 = 0xe8ed5112fb6abd78ULL;
};

template<class ContainerAllocator>
struct DataType< ::agrosim::distributed_<ContainerAllocator> >
{
  static const char* value()
  {
    return "agrosim/distributed";
  }

  static const char* value(const ::agrosim::distributed_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::agrosim::distributed_<ContainerAllocator> >
{
  static const char* value()
  {
    return "int32 Id\n"
"float64 pos_x\n"
"float64 pos_y\n"
"float64[] Costs\n"
"int32[] taskdone\n"
"\n"
;
  }

  static const char* value(const ::agrosim::distributed_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::agrosim::distributed_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.Id);
      stream.next(m.pos_x);
      stream.next(m.pos_y);
      stream.next(m.Costs);
      stream.next(m.taskdone);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct distributed_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::agrosim::distributed_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::agrosim::distributed_<ContainerAllocator>& v)
  {
    s << indent << "Id: ";
    Printer<int32_t>::stream(s, indent + "  ", v.Id);
    s << indent << "pos_x: ";
    Printer<double>::stream(s, indent + "  ", v.pos_x);
    s << indent << "pos_y: ";
    Printer<double>::stream(s, indent + "  ", v.pos_y);
    s << indent << "Costs[]" << std::endl;
    for (size_t i = 0; i < v.Costs.size(); ++i)
    {
      s << indent << "  Costs[" << i << "]: ";
      Printer<double>::stream(s, indent + "  ", v.Costs[i]);
    }
    s << indent << "taskdone[]" << std::endl;
    for (size_t i = 0; i < v.taskdone.size(); ++i)
    {
      s << indent << "  taskdone[" << i << "]: ";
      Printer<int32_t>::stream(s, indent + "  ", v.taskdone[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // AGROSIM_MESSAGE_DISTRIBUTED_H
