// Generated by gencpp from file agrosim/neighbour.msg
// DO NOT EDIT!


#ifndef AGROSIM_MESSAGE_NEIGHBOUR_H
#define AGROSIM_MESSAGE_NEIGHBOUR_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace agrosim
{
template <class ContainerAllocator>
struct neighbour_
{
  typedef neighbour_<ContainerAllocator> Type;

  neighbour_()
    : Id()
    , Task()
    , row(0)
    , column(0)
    , costs()  {
    }
  neighbour_(const ContainerAllocator& _alloc)
    : Id(_alloc)
    , Task(_alloc)
    , row(0)
    , column(0)
    , costs(_alloc)  {
  (void)_alloc;
    }



   typedef std::vector<int32_t, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<int32_t>> _Id_type;
  _Id_type Id;

   typedef std::vector<int32_t, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<int32_t>> _Task_type;
  _Task_type Task;

   typedef int32_t _row_type;
  _row_type row;

   typedef int32_t _column_type;
  _column_type column;

   typedef std::vector<double, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<double>> _costs_type;
  _costs_type costs;





  typedef boost::shared_ptr< ::agrosim::neighbour_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::agrosim::neighbour_<ContainerAllocator> const> ConstPtr;

}; // struct neighbour_

typedef ::agrosim::neighbour_<std::allocator<void> > neighbour;

typedef boost::shared_ptr< ::agrosim::neighbour > neighbourPtr;
typedef boost::shared_ptr< ::agrosim::neighbour const> neighbourConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::agrosim::neighbour_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::agrosim::neighbour_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::agrosim::neighbour_<ContainerAllocator1> & lhs, const ::agrosim::neighbour_<ContainerAllocator2> & rhs)
{
  return lhs.Id == rhs.Id &&
    lhs.Task == rhs.Task &&
    lhs.row == rhs.row &&
    lhs.column == rhs.column &&
    lhs.costs == rhs.costs;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::agrosim::neighbour_<ContainerAllocator1> & lhs, const ::agrosim::neighbour_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace agrosim

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::agrosim::neighbour_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::agrosim::neighbour_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::agrosim::neighbour_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::agrosim::neighbour_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::agrosim::neighbour_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::agrosim::neighbour_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::agrosim::neighbour_<ContainerAllocator> >
{
  static const char* value()
  {
    return "056719dbb8917202f0bca8112a07cd79";
  }

  static const char* value(const ::agrosim::neighbour_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x056719dbb8917202ULL;
  static const uint64_t static_value2 = 0xf0bca8112a07cd79ULL;
};

template<class ContainerAllocator>
struct DataType< ::agrosim::neighbour_<ContainerAllocator> >
{
  static const char* value()
  {
    return "agrosim/neighbour";
  }

  static const char* value(const ::agrosim::neighbour_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::agrosim::neighbour_<ContainerAllocator> >
{
  static const char* value()
  {
    return "int32[] Id\n"
"int32[] Task\n"
"int32 row\n"
"int32 column\n"
"float64[]  costs\n"
;
  }

  static const char* value(const ::agrosim::neighbour_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::agrosim::neighbour_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.Id);
      stream.next(m.Task);
      stream.next(m.row);
      stream.next(m.column);
      stream.next(m.costs);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct neighbour_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::agrosim::neighbour_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::agrosim::neighbour_<ContainerAllocator>& v)
  {
    s << indent << "Id[]" << std::endl;
    for (size_t i = 0; i < v.Id.size(); ++i)
    {
      s << indent << "  Id[" << i << "]: ";
      Printer<int32_t>::stream(s, indent + "  ", v.Id[i]);
    }
    s << indent << "Task[]" << std::endl;
    for (size_t i = 0; i < v.Task.size(); ++i)
    {
      s << indent << "  Task[" << i << "]: ";
      Printer<int32_t>::stream(s, indent + "  ", v.Task[i]);
    }
    s << indent << "row: ";
    Printer<int32_t>::stream(s, indent + "  ", v.row);
    s << indent << "column: ";
    Printer<int32_t>::stream(s, indent + "  ", v.column);
    s << indent << "costs[]" << std::endl;
    for (size_t i = 0; i < v.costs.size(); ++i)
    {
      s << indent << "  costs[" << i << "]: ";
      Printer<double>::stream(s, indent + "  ", v.costs[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // AGROSIM_MESSAGE_NEIGHBOUR_H
