(cl:defpackage agrosim-msg
  (:use )
  (:export
   "<CENTRALISED>"
   "CENTRALISED"
   "<CENTRALISED>"
   "CENTRALISED"
   "<DESCENTRALISED>"
   "DESCENTRALISED"
   "<DESCENTRALISED>"
   "DESCENTRALISED"
   "<DISTRIBUTED>"
   "DISTRIBUTED"
   "<DISTRIBUTED>"
   "DISTRIBUTED"
   "<NEIGHBOUR>"
   "NEIGHBOUR"
   "<NEIGHBOUR>"
   "NEIGHBOUR"
  ))

